// Generated by Wrangler on Mon Jul 22 2024 08:52:52 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  CF_CMS_KV: KVNamespace,
  DB: D1Database
}
